version: '3'
services:
        web:
                image: flask_vase_port
                build: .
                ports:
                        - "8094:8080"
                volumes:
                        - persistent_volume:/app/volumes
volumes:
  persistent_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/p3t1_vase/volumes
